"use client"
import '@ant-design/v5-patch-for-react-19';
import "./globals.css"
import { Provider } from "react-redux"
import { store } from "././store/store"
import Nav from "./layout/nav"

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Nav></Nav>
          <main className="main-container">
            layoutPage
            {children}
          </main>
        </Provider>
      </body>
    </html>
    
  );
}
